Thinkpad toolkit: libthinkpad.c File Reference
libthinkpad.c File Reference
#include <stdio.h>
#include <errno.h>
#include <wait.h>
#include <unistd.h>
#include "libthinkpad.h"
Data Structures
struct Morsecode
Defines
#define MORSPOINT blinkLight(morse->point, 0, 1);
#define MORSLINE blinkLight(morse->line, 0, 1);
Functions
int blinkLight (int on, int off, int num)
int blinkMorseChar (char c)
int blinkMorseString (char c[])
Variables
struct Morsecode morsecode
Define Documentation
#define MORSLINE blinkLight(morse->line, 0, 1);
Definition at line 37 of file libthinkpad.c.
Referenced by blinkMorseChar().
#define MORSPOINT blinkLight(morse->point, 0, 1);
Definition at line 36 of file libthinkpad.c.
Referenced by blinkMorseChar().
Function Documentation
int blinkLight (int on, int off, int num)
Switch the light over the lcd on and off (blinking).
Parameters:
on The time how long the light is switched on
off The time how long the light is switched off
num How often the light switching between on and off
Returns:
The return value is 0 if all is okay or -1 if they was an error
Definition at line 50 of file libthinkpad.c.
References LIGHTPROC.
Referenced by main().
int blinkMorseChar (char c)
This function takes a char, and blinks than the letter in morsecode. Morsecode ("." = short alias point, "-" = long alias line):
a -> .- n -> -. b -> -... o -> --- c -> -.-. p -> .--. d -> -.. q -> --.- e -> . r -> .-. f -> ..-. s -> ... g -> --. t -> - h -> .... u -> ..- i -> .. v -> ...- j -> .--- w -> .-- k -> -.- x -> -..- l -> .-.. y -> -.-- m -> -- z -> --..
1 -> .---- 6 -> -.... 2 -> ..--- 7 -> --... 3 -> ...-- 8 -> ---.. 4 -> ....- 9 -> ----. 5 -> ..... 0 -> -----
Parameters:
c The char for the morsecode
Returns:
int The return value is 0 if all is okay or -1 if they was an error
Definition at line 75 of file libthinkpad.c.
References Morsecode::line, morsecode, MORSLINE, MORSPOINT, Morsecode::pause, Morsecode::pausechar, Morsecode::pauseword, and Morsecode::point.
Referenced by blinkMorseString(), and main().
int blinkMorseString (char c[])
Definition at line 407 of file libthinkpad.c.
References blinkMorseChar(), Morsecode::line, morsecode, Morsecode::pause, Morsecode::pausechar, Morsecode::pauseword, and Morsecode::point.
Referenced by main().
Variable Documentation
struct Morsecode morsecode
Referenced by blinkMorseChar(), and blinkMorseString().