Thinkpad toolkit: thinkpadTest.c File Reference
thinkpadTest.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include <signal.h>
#include <wait.h>
#include "libthinkpad.h"
Defines
#define ERR error_handler
#define STRLENGTH 1024
#define FALSE 0
#define TRUE !FALSE
Typedefs
typedef int boolean
Functions
int error_handler (char *fctname, int errornb)
int help_function (int argc, char *argv[])
void showWarranty ()
void showLicense ()
int main (int argc, char *argv[])
Define Documentation
#define ERR error_handler
Definition at line 32 of file thinkpadTest.c.
#define FALSE 0
Definition at line 36 of file thinkpadTest.c.
#define STRLENGTH 1024
Definition at line 34 of file thinkpadTest.c.
#define TRUE !FALSE
Definition at line 37 of file thinkpadTest.c.
Typedef Documentation
typedef int boolean
Definition at line 39 of file thinkpadTest.c.
Function Documentation
int error_handler (char * fctname, int errornb)
Definition at line 108 of file thinkpadTest.c.
int help_function (int argc, char * argv[])
Definition at line 118 of file thinkpadTest.c.
References LIGHTPROC.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 49 of file thinkpadTest.c.
References blinkLight(), blinkMorseChar(), blinkMorseString(), help_function(), showLicense(), and showWarranty().
void showLicense ()
Definition at line 141 of file thinkpadTest.c.
Referenced by main().
void showWarranty ()
Definition at line 137 of file thinkpadTest.c.
Referenced by main().